name: Run UnitTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml  # Using conda environment YAML file
          activate-environment: TreeMS2  # The name of the environment
          python-version: 3.12  # Set Python version

      # Step 3: Run tests
      - name: Run unittests
        shell: bash -l {0}  # Ensure conda env is activated properly
        run: |
          python -m unittest discover -s tests
